[package]
name = "lura"
version = "0.1.0"
authors = ["Nicholas A. Zigarovich <nick@zigarovich.io>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/ecks0/lura-rs"
repository = "https://github.com/ecks0/lura-rs"
readme = "README.md"
description = "Devops development helpers"

[dependencies]
thiserror = "1.0.20"
anyhow = "1.0.31"

num = "0.3.0"
num-traits = "0.2.12"
rand = "0.7.3"

serde = "1.0.114"
serde_json = "1.0.56"
toml = "0.5.6"

async-std = { version = "1.6.2" }
tokio-compat = { version = "0.1.6" }

[dependencies.tokio]
version = "0.2.21"
features = [
  "io-driver",
  "io-util",
  "process",
  "time",
]
