[package]
name = "lura"
version = "0.1.0"
authors = ["Nicholas A. Zigarovich <nick@zigarovich.io>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/ecks0/lura-rs"
repository = "https://github.com/ecks0/lura-rs"
readme = "README.md"
description = "Devops development helpers"

[dependencies]
thiserror = "1.0.20"
num = "0.3.0"
num-traits = "0.2.12"
serde = "1.0.114"
anyhow = "1.0.31"
tokio = { version = "0.2.21", features = ["full"] }
async-std = "1.6.2"
